# Generated by Django 5.1.4 on 2024-12-31 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
